name: core
description: A core module.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  equatable: ^1.0.2
  http: ^0.12.0+4
  meta: ^1.1.6
  sqflite: ^1.3.0
  path_provider: ^1.6.5
  shared_preferences: ^0.5.8
  logger: ^0.9.2
  get_it: ^3.0.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter